server:
  port: 8082
spring:
  datasource:
    password: GYBv587.521
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Myself?useUnicode=true&amp&characterEncoding=utf8&amp&serverTimezone=GMT%2b8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.gyb.springbootdemo.dao: debug